CarShop/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarShop.Models;
using System.Runtime.ConstrainedExecution;
using System.Net;
using CarShop.Interfaces;
using CarShop.Services;
using Microsoft.AspNetCore.Routing;
using static Org.BouncyCastle.Crypto.Engines.SM2Engine;
using Microsoft.AspNetCore.Authorization;

namespace CarShop.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ICarService _carService;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public CarsController(ICategoryService categoryService, ICarService carService, IWebHostEnvironment hostEnvironment)
        {
            _categoryService = categoryService;
            _carService = carService;
            _hostingEnvironment = hostEnvironment;
        }


        // GET: Cars
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Index()
        {
            var response = await _carService.GetCarsAsync();
            return View(response.Data);
        }

        // GET: Cars/Details/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var response = await _carService.GetCarAsync((int)id);
            var car = response.Data;

            if (car == null)
                return NotFound();

            //messanger.SendMessage("Hello! It is car shop", new Models.User() { UserName = "Kos", Email = "turchak@sweetondale.cz" }, "Car shop");
            return View(car);
        }

        // GET: Cars/CarDetails/5
        public async Task<IActionResult> CarDetails(int? id)
        {
            if (id == null)
                return NotFound();

            var response = await _carService.GetCarAsync((int)id);
            var car = response.Data;

            if (car == null)
                return NotFound();

            return View(car);
        }

        // GET: Cars/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,LongDesc,ShortDesc,Title,Url,Price,IsFavourite,Count, CategoryId")] Car car)
        {
            if (!ModelState.IsValid)
                return View(car);

            var response = await _carService.CreateCarAsync(car);
            if (response.StatusCode == HttpStatusCode.Created)
                return RedirectToAction(nameof(Index));

            return Problem("Something happened wrong",null, (int)response.StatusCode);
        }

        // GET: Cars/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var response = await _carService.GetCarAsync((int)id);
            var car = response.Data;

            if (car == null)
                return NotFound();

            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to. [Bind("Id,Name,ShortDesc,LongDesc,Title,Url,Price,IsFavourite,Count")]
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.  [Bind("Id,Name,ShortDesc,LongDesc,Title,Url,Price,CategoryId")]
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,LongDesc,ShortDesc,Title,Url,Price,IsFavourite,Count, CategoryId")] Car car)
        {
            if (id != car.Id)
                return NotFound();

            if (!ModelState.IsValid)
                return View(car);

            var response = await _carService.UpdateCarAsync(car);

            if (response.StatusCode == HttpStatusCode.OK)
                return RedirectToAction(nameof(Index));

            return View(car);
        }

        // GET: Cars/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var response = await _carService.GetCarAsync((int)id);
            var car = response.Data;

            if (car == null)
                return NotFound(response.Message);

            return View(car);
        }

        // POST: Cars/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var response = await _carService.GetCarAsync((int)id);
            var car = response.Data;

            if(car == null)
                return NotFound();

            var delResponse = await _carService.DeleteCarAsync((int)id);

            if (delResponse.Data)
                return RedirectToAction(nameof(Index));

            return StatusCode((int)delResponse.StatusCode, delResponse.Message);
        }

        [HttpPost]
        public async Task<IActionResult> CarFilter([FromBody]CarsFilter filter)
        {
            if (filter == null)
                return NotFound();

            var response = await _carService.PostFilterredCarsAsync(filter);
            if(response.StatusCode != HttpStatusCode.OK)
                return NotFound();

            var filterredCars = response.Data ?? new List<Car>();

            string htmlText = "";

            foreach (var car in filterredCars)
            {
                htmlText += $"<div class=\"col-xxl-4 col-lg-6 col-md-12 p-2 mt-5\">" +
                        $"<img src = \"{car.Url}\" alt=\"{car.Name}\">" +
                        $"<div class=\"text-center p-2\">" +
                            $"<h3>{car.Name}</h3>" +
                            $"<p>{car.Title}</p>" +
                            $"<p>{car.ShortDesc}</p>" +
                            $"<p>Price: $ {car.Price}</p>" +
                            $"<a href=\"/Cars/CarDetails/{car.Id}\" class=\"manageBtn btn btn-info text-center\">More details</a>" +
                            $"<a href= \"/Cart/AddItem/?carId={car.Id}\" class=\"manageBtn btn btn-success text-center mx-2\">Bye</a>" +
                        $"</div>" +
                    $"</div>";
            }

            return StatusCode(200, htmlText);
        }

        private string GetTextHtmlCarCard()
        {
            var pathPartialView = _hostingEnvironment.ContentRootPath + "/Views/Shared/_CarCard.cshtml";

            if (System.IO.File.Exists(pathPartialView))
            {
                var content = System.IO.File.ReadAllText(pathPartialView);
                // Делайте что-то с содержимым файла
                return content;
            }
            else
            {
                // Обработка ситуации, когда файл не найден
                return string.Empty;
            }
        }
    }
}

CarShop/Controllers/RolesController.cs
using CarShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarShop.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        private HttpClient httpClient = new HttpClient();

        // GET: RolesController
        public async Task<ActionResult> Index()
        {
            return View(await httpClient.GetFromJsonAsync<IEnumerable<Role>>($"{Api.apiUri}roles"));
        }

        // GET: RolesController/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var role = await httpClient.GetFromJsonAsync<Role>($"{Api.apiUri}role/{id}");

            if (role == null)
                return NotFound();

            return View(role);
        }

        // GET: RolesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RolesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id,Name")] Role role)
        {
            if (string.IsNullOrEmpty(role.Name))
                ModelState.AddModelError(nameof(role.Name), "Enter role name");

            if (ModelState.IsValid)
            {
                
                var response = await httpClient.PostAsJsonAsync($"{Api.apiUri}roles", role);

                if (response.IsSuccessStatusCode)
                    return RedirectToAction(nameof(Index));
                else
                    return BadRequest();
            }
            return View(role);
        }

        // GET: RolesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RolesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var role = await httpClient.GetFromJsonAsync<Role>($"{Api.apiUri}roles/{id}");

            if (role == null)
                return NotFound();

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Role role)
        {
            if (id != role.Id)
                return NotFound();

            if (string.IsNullOrEmpty(role.Name))
                ModelState.AddModelError(nameof(role.Name), "Enter role name");

            if (ModelState.IsValid)
            {
                var response = await httpClient.PutAsJsonAsync($"{Api.apiUri}roles/{id}", role);

                if (response == null)
                    return NotFound();

                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: RolesController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var role = await httpClient.GetFromJsonAsync<Role>($"{Api.apiUri}roles/{id}");

            if (role == null)
                return NotFound();

            return View(role);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await httpClient.GetFromJsonAsync<Role>($"{Api.apiUri}roles/{id}");
            if (role == null)
                return NotFound();

            await httpClient.DeleteAsync($"{Api.apiUri}roles/{id}");

            return RedirectToAction(nameof(Index));
        }
    }
}

CarShop/Views/Shared/Accessdenied.cshtml
<p class="text-center"><b>You do not have access to this page</b></p>
<p class="text-center">Contact the administrator</p>
<div class="text-center">
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back to home page</a>
</div>

CarShop/Views/Shared/_CarCard.cshtml
@model Car

<div class="col-xxl-4 col-lg-6 col-md-12 p-2 mt-5">
    <img src="@Model.Url" alt="@Model.Name">
    <div class="text-center p-2">
        <h3>@Model.Name</h3>
        <p>@Model.Title</p>
        <p>@Model.ShortDesc</p>
        <p>Price: $ @Model.Price</p>
        <a asp-controller="Cars" asp-action="CarDetails" asp-route-id="@Model.Id" class="manageBtn btn btn-info text-center">More details</a>
        <a asp-controller="Cart" asp-action="AddItem" asp-route-carId="@Model.Id" class="manageBtn btn btn-success text-center mx-2">Bye</a>
    </div>
</div>

CarShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>lessons 3</title>
	<link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" type="text/css" />
	<link rel="stylesheet" href="/css/site.css" type="text/css" />
    @RenderSection("Styles", false)
</head>
<body class="bg-dark">
	<header>
		<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark shadow">
            <div class="container-fluid">
                <a class="navbar-brand" href="/Home/Index">Car shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/Home/CarList">Car list</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Database management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a asp-controller="Roles" asp-action="Index" class="dropdown-item">Roles</a></li>
                                <li><a asp-controller="Users" asp-action="Index" class="dropdown-item">Users</a></li>
                                <li><a asp-controller="Cars" asp-action="Index" class="dropdown-item">Cars</a></li>
                                <li><a asp-controller="Categories" asp-action="Index" class="dropdown-item">Categories</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Account
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a asp-controller="Account" asp-action="Login" class="dropdown-item">Login</a></li>
                                <li><a asp-controller="Account" asp-action="Register" class="dropdown-item">Register</a></li>
                                <li><a asp-controller="Account" asp-action="Logout" class="dropdown-item">Logout</a></li>
                                <li><a asp-controller="Home" asp-action="PersonalArea" class="dropdown-item">Personal area</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="nav-link position-relative" asp-controller="Cart" asp-action="Index">
                                Cart 
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                    0
                                </span>
                            </a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
		</nav>
	</header>
	<div class="root">
		@RenderBody()
	</div>
    <footer class="footer">

    </footer>
	<script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
	<script src="/js/site.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>